import type { Rule } from "../../shared/types";

/** Baseline rule merged beneath built-in and user site rules. */
export const generalRule: Rule = {
  id: "general",
  matches: ["<all_urls>"],
  selectors: [],
  excludeSelectors: [".notranslate", "[translate='no']", "[contenteditable]"],
  stayOriginalSelectors: [],
  atomicBlockSelectors: [],
  extraInlineSelectors: [],
  extraBlockSelectors: [],
  shadowRootSelectors: [],
  mutationExcludeSelectors: ["[data-imt]"],
  injectedCss: [],
  excludeTags: [
    "TITLE",
    "LINK",
    "SCRIPT",
    "STYLE",
    "TEXTAREA",
    "SVG",
    "G",
    "NOSCRIPT",
    "BASE",
    "PRE",
    "KBD",
    "WBR",
    "RT",
    "RP",
    "META",
    "MATH",
  ],
  stayOriginalTags: [
    "CODE",
    "TT",
    "IMG",
    "SUP",
    "SUB",
    "SAMP",
    "math",
    "semantics",
    "mrow",
    "mo",
    "mfrac",
    "msup",
    "mi",
    "mn",
    "msqrt",
  ],
  inlineTags: [
    "A",
    "ABBR",
    "FONT",
    "ACRONYM",
    "B",
    "INS",
    "DEL",
    "RUBY",
    "RP",
    "RB",
    "BDO",
    "MARK",
    "BIG",
    "RT",
    "NOBR",
    "CITE",
    "DFN",
    "EM",
    "I",
    "LABEL",
    "Q",
    "S",
    "SMALL",
    "SPAN",
    "STRONG",
    "SUB",
    "SUP",
    "U",
    "KBD",
    "TT",
    "VAR",
    "IMG",
    "CODE",
    "TIME",
    "WBR",
  ],
  allBlockTags: [
    "BODY",
    "HGROUP",
    "ADDRESS",
    "ARTICLE",
    "ASIDE",
    "DETAILS",
    "BLOCKQUOTE",
    "SELECT",
    "OPTION",
    "CANVAS",
    "DD",
    "DL",
    "DT",
    "FIELDSET",
    "FIGCAPTION",
    "FIGURE",
    "FOOTER",
    "HEADER",
    "FORM",
    "HR",
    "MAIN",
    "SUMMARY",
    "NAV",
    "NOSCRIPT",
    "PRE",
    "SECTION",
    "TABLE",
    "TFOOT",
    "UL",
    "VIDEO",
    "P",
    "DIV",
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "LI",
    "OL",
    "BR",
    "PICTURE",
    "TBODY",
    "TR",
    "TD",
    "TH",
    "SOURCE",
    "BUTTON",
  ],
  isTranslateTitle: true,
  paragraphMinTextCount: 2,
  blockMinTextCount: 24,
  lineBreakMaxTextCount: 0,
  targetWrapperTag: "font",
  wrapperPrefix: "smart",
  wrapperSuffix: "smart",
  sameLangCheck: true,
  enableRichTranslate: true,
  glossaries: [],
  translationMode: "dual",
  theme: "underline",
};
