// Generated by scripts/port-rules.ts from Immersive Translate 1.32.7.
// Do not edit by hand; change the curated list or mapper and rerun the script.
import type { Rule } from "../../../shared/types";

export const ai_productivityRules = [
  {
    id: "ported-gmail",
    matches: ["*://mail.google.com/*"],
  },
  {
    excludeSelectors: [
      ".jHAG3.XG5Jd",
      ".OZZZK",
      ".lDdSm",
      ".ZfoST.VlT6S.azUpZ",
      ".GssDD,.xpAva,.oHwUF,.D1eg_",
      "[id=CenterRegion]",
      "[id=RibbonRoot]",
      "[role=toolbar]",
      ".qQbyL,.bkYAr,.gpJ9q,.threeColumnCirclePersonaDivWidth",
      "[class='_rWRU Ejrkd qq2gS D8iyG']",
    ],
    id: "ported-outlook",
    matches: ["*://outlook.live.com/*", "*://outlook.office.com/*"],
  },
  {
    selectorMatches: [".notion-html body", ".notion-app"],
    excludeSelectors: [".notion-code-block"],
    injectedCss: ["[aria-label='Templates'] font br {display:none;}"],
    id: "ported-notion",
    matches: ["*://www.notion.so/*", "*://*.notion.site/*"],
  },
  {
    id: "ported-figma",
    matches: ["*://www.figma.com/*", "*://help.figma.com/*"],
  },
  {
    excludeSelectors: [
      "div.absolute.bottom-0.left-0.w-full",
      "h1",
      "div#headlessui-portal-root",
      "nav",
      "ul[aria-multiselectable]",
      ".markdown *",
      "div[class='flex flex-col items-start']",
      "div[class='flex items-center justify-center gap-1 border-b border-black/10 bg-gray-50 p-3 text-gray-500 dark:border-gray-900/50 dark:bg-gray-700 dark:text-gray-300']",
    ],
    isTranslateTitle: false,
    wrapperPrefix: "",
    enableRichTranslate: false,
    id: "ported-chatgpt",
    matches: ["*://chatgpt.com/*", "*://chat.openai.com/*"],
  },
  {
    id: "ported-claude",
    matches: ["*://claude.ai/*"],
  },
  {
    id: "ported-gemini",
    matches: ["*://gemini.google.com/*"],
  },
  {
    excludeMatches: [
      "https://www.perplexity.ai/hub/*",
      "https://www.perplexity.ai/*/hub/*",
      "https://www.perplexity.ai/onboarding",
      "https://www.perplexity.ai/enterprise*",
      "https://www.perplexity.ai/2024recap",
    ],
    additionalStayOriginalSelectors: [
      "a.citation",
      "[class='my-md pb-xs pt-sm']",
    ],
    additionalExcludeSelectors: ["[data-framer-name='Desktop']"],
    id: "ported-perplexity",
    matches: ["*://www.perplexity.ai/*", "*://perplexity.ai/*"],
  },
  {
    id: "ported-phind",
    matches: ["*://www.phind.com/*", "*://phind.com/*"],
  },
  {
    excludeSelectors: [
      ".Markdown_markdownContainer__Tz3HQ *",
      ".MarkdownLink_linkifiedLink__KxC9G",
      "menu",
      "aside",
    ],
    id: "ported-poe",
    matches: ["*://poe.com/*"],
  },
  {
    additionalExcludeSelectors: [
      ".ui-box .ui-box[class='ui-box']",
      "[data-tid='author']",
      ".fui-ChatMessageCompact__author",
    ],
    additionalMutationExcludeSelectors: [".ui-box .ui-box[class='ui-box'] *"],
    additionalExtraInlineSelectors: ["[data-tid='closed-caption-text']"],
    additionalStayOriginalSelectors: [
      "span[title][style='min-width: 20px; height: 20px;']",
    ],
    id: "ported-microsoft-teams",
    matches: ["*://teams.microsoft.com/*", "*://teams.live.com/*"],
  },
  {
    additionalExcludeSelectors: [".iOzk7[jsname='dsyhDe']", ".ygicle.VbkSUe"],
    additionalMutationExcludeSelectors: [".iOzk7[jsname='dsyhDe'] *"],
    additionalExtraInlineSelectors: [".ygicle.VbkSUe"],
    id: "ported-google-meet",
    matches: ["*://meet.google.com/*"],
  },
  {
    additionalExcludeSelectors: [".live-transcription-subtitle__box"],
    additionalMutationExcludeSelectors: [".live-transcription-subtitle__box *"],
    additionalExtraInlineSelectors: [".live-transcription-subtitle__item"],
    id: "ported-zoom",
    matches: ["*://*.zoom.us/*"],
  },
  {
    additionalExcludeSelectors: [".catalogue__list"],
    id: "ported-feishu-lark",
    matches: [
      "*://*.feishu.cn/*",
      "*://*.larksuite.com/*",
      "*://*.larkoffice.com/*",
    ],
  },
  {
    selectors: [
      "[id=descriptionmodule]",
      "[id=summary-val]",
      "div.action-body",
      "td.stsummary",
    ],
    id: "ported-jira",
    matches: ["*://*.atlassian.net/*", "*://jira.*.com/*"],
  },
  {
    id: "ported-confluence",
    matches: ["*://*.atlassian.net/wiki/*"],
  },
  {
    additionalExcludeSelectors: [
      ".mx_DisambiguatedProfile",
      ".mx_ReplyChain_wrapper",
      ".mx_ThreadSummary_replies_amount",
    ],
    id: "ported-element",
    matches: ["*://app.element.io/*"],
  },
  {
    selectors: [
      ".article_header_title",
      ".article_title_link",
      ".article_content",
      ".article_magazine_title_link",
      ".blog-post-page",
      "#welcome_center",
      ".gad_overview_articles_wrapper",
      ".library_article_text h4",
      ".header_name",
      ".blog-content",
    ],
    excludeMatches: [
      "https://www.inoreader.com/features*",
      "https://www.inoreader.com/blog*",
      "https://www.inoreader.com/discover*",
      "https://www.inoreader.com/contact*",
      "https://www.inoreader.com/pricing*",
      "https://www.inoreader.com/enterprise*",
    ],
    additionalInjectedCss: [
      ".article_title_link,.library_article_text h4,.gadget_overview_article_title,.article_magazine_title_link,.reader_pane_view_style_2 .column_view_title {-webkit-line-clamp: unset!important;max-height: unset!important;}",
      ".article_tile_content_wraper,div.article_tile {overflow:auto}",
      ".article_header_title {white-space:normal;max-height: unset!important;}",
      ".article_header_title span {display:flex !important;flex-direction: column;}",
      ".ar.article_no_thumbnail,[data-type=article] {height:unset!important;}",
      ".view_style_2 #reader_pane .ar .article_header_text .column_view_info {position:relative!important;}",
    ],
    id: "ported-inoreader",
    matches: ["*://www.inoreader.com/*", "*://*.inoreader.com/*"],
  },
] as const satisfies readonly Rule[];
