// Generated by scripts/port-rules.ts from Immersive Translate 1.32.7.
// Do not edit by hand; change the curated list or mapper and rerun the script.
import type { Rule } from "../../../shared/types";

export const commerceRules = [
  {
    paragraphMinTextCount: 4,
    additionalExtraBlockSelectors: [
      ".a-size-small.a-link-normal.page-banner-link.a-nowrap",
    ],
    additionalInjectedCss: [
      ".a-carousel-viewport {height:unset;}",
      "[class*='clamp'] {max-height: unset!important;-webkit-line-clamp: unset!important;}",
      "[data-rows] {max-height: unset!important;-webkit-line-clamp: unset!important;}",
      "[data-a-expander-name='review_text_read_more'] { max-height: unset;}",
      ".compact.primaryText.primaryTextOnly {max-height: unset;-webkit-line-clamp: unset;}",
      ".format {-webkit-line-clamp: unset;}",
      ".dcl-truncate,[class*='textButton'],span[data-a-max-rows] {max-height:unset!important;-webkit-line-clamp: unset!important;}",
      ".a-reactive-container-transition,.a-cardui-uninitialized {height:unset!important;max-height:unset!important;}",
    ],
    additionalExcludeSelectors: [
      "#navFooter",
      ".s-price-instructions-style",
      "[class*='-star ']",
      "[data-hook='acr-average-stars-rating-text']",
      ".a-color-price,.a-price",
      "[data-testid='price-section']",
      "[data-component='dui-badge']",
      "#glow-ingress-block,#nav-link-accountList,#nav-orders,#nav-cart",
      ".a-profile-content,[data-hook=product-variation-attributes],[data-hook=helpfulVoteWidget],[data-hook=reportAbuseButton],[data-hook=helpful-vote-statement]",
    ],
    id: "ported-amazon",
    matches: [
      "*://www.amazon.com/*",
      "*://*.amazon.com/*",
      "*://*.amazon.co.uk/*",
      "*://*.amazon.co.jp/*",
    ],
  },
  {
    excludeSelectors: [
      "headers",
      "[itemprop=offers]",
      ".dne-itemtile-original-price",
    ],
    paragraphMinTextCount: 4,
    additionalInjectedCss: [
      ".iS4T .zgfQ .uHzw .Ep66 {-webkit-line-clamp: unset;max-height: unset;}",
      "[itemprop=name],.merch-item-title {-webkit-line-clamp: unset;max-height: unset;}",
    ],
    id: "ported-ebay",
    matches: ["*://www.ebay.com/*", "*://*.ebay.com/*"],
  },
  {
    additionalInjectedCss: [
      "[class*='multi--title'],.G7dOC {-webkit-line-clamp:unset;}",
    ],
    additionalExcludeSelectors: ["[class*='multi--price']"],
    id: "ported-aliexpress",
    matches: ["*://www.aliexpress.com/*", "*://*.aliexpress.com/*"],
  },
  {
    additionalInjectedCss: [
      ".WBVL_7,.ellipsis-content {-webkit-line-clamp:unset!important;}",
    ],
    id: "ported-shopee",
    matches: ["*://shopee.*/*", "*://*.shopee.*/*"],
  },
  {
    id: "ported-steam",
    matches: ["*://store.steampowered.com/*", "*://steamcommunity.com/*"],
  },
  {
    id: "ported-epic-games",
    matches: ["*://store.epicgames.com/*", "*://www.epicgames.com/*"],
  },
  {
    selectors: [".message-body", "article[data-testid=index-container]"],
    additionalExcludeSelectors: [
      "[data-testid=basic-message-header]",
      "[data-testid=message-header-timestamp]",
      "time",
      ".user-name",
      ".user-info",
      ".header",
    ],
    id: "ported-fiverr",
    matches: ["*://www.fiverr.com/*", "*://*.fiverr.com/*"],
  },
  {
    id: "ported-tripadvisor",
    matches: ["*://www.tripadvisor.com/*", "*://*.tripadvisor.com/*"],
  },
] as const satisfies readonly Rule[];
