// Generated by scripts/port-rules.ts.
import { academicRules } from "./academic";
import { ai_productivityRules } from "./ai-productivity";
import { commerceRules } from "./commerce";
import { developerRules } from "./developer";
import { newsRules } from "./news";
import { searchRules } from "./search";
import { socialRules } from "./social";
import { videoRules } from "./video";

export const generatedRules = [
  ...academicRules,
  ...ai_productivityRules,
  ...commerceRules,
  ...developerRules,
  ...newsRules,
  ...searchRules,
  ...socialRules,
  ...videoRules,
] as const;
