// Generated by scripts/port-rules.ts from Immersive Translate 1.32.7.
// Do not edit by hand; change the curated list or mapper and rerun the script.
import type { Rule } from "../../../shared/types";

export const newsRules = [
  {
    selectorMatches: ["meta[property='al:ios:url'][content^='medium://']"],
    selectors: [
      "h1,h2,h3",
      "article section",
      "[aria-hidden='false'] pre",
      "article p",
      ".postMetaInline",
      "a .u-fontSize24",
      "pre .ha",
      "pre > div > div > div",
      "div > p > span",
      "section p,section span",
      "a div span",
      ".ppapp-form-info,.request-form",
    ],
    excludeSelectors: [
      "[aria-label='Post Preview Reading Time']",
      ".speechify-ignore",
      "article pre",
    ],
    injectedCss: [
      ".u-lineClamp4,.u-lineClamp3,.u-lineClamp2 {-webkit-line-clamp:unset!important;max-height:unset!important;}",
    ],
    additionalExcludeSelectors: ["pre > span"],
    id: "ported-medium",
    matches: ["*://medium.com/*", "*://*.medium.com/*"],
  },
  {
    selectorMatches: [
      "link[href^='https://substackcdn.com/bundle/'][rel=preload]",
    ],
    excludeSelectors: [
      ".publication-footer",
      ".subscribe-footer",
      ".main-menu",
      ".navbar-title-link",
      "[data-testid='navbar']",
      ".navbar-title",
      ".captioned-button-wrap",
      ".subscription-widget-wrap",
      ".tweet-header",
      ".tweet-link-bottom",
      ".expanded-link",
      ".meta-subheader",
      ".comment-meta",
      ".comment-actions",
    ],
    additionalExtraBlockSelectors: [
      ".reader2-post-title",
      ".tweet-link-top",
      ".tweet-link-bottom",
      ".expanded-link",
    ],
    id: "ported-substack",
    matches: ["*://*.substack.com/*"],
  },
  {
    excludeSelectors: [
      "#app > div > div > header",
      "#app > div > div > div > div > header",
      "#in-story-masthead",
      "[data-testid=masthead-container]",
    ],
    injectedCss: [
      "a::after {position:relative!important;}",
      "footer {line-height: unset!important;;}",
    ],
    additionalExcludeSelectors: [
      "[data-testid=user-header]",
      "[data-testid^='recommend-button']",
      "[data-testid=copy-link]",
      ".css-mydst6 > a",
    ],
    id: "ported-nytimes",
    matches: ["*://www.nytimes.com/*", "*://nytimes.com/*"],
  },
  {
    additionalExcludeSelectors: [
      "section.module--languages",
      ".drop-capped",
      ".smp-toucan-player",
      "smp-subtitles",
      "#subtitle_subtitle2",
    ],
    additionalMutationExcludeSelectors: [
      "[data-testid='media-player-container-landscape'] *",
    ],
    id: "ported-bbc",
    matches: ["*://*.bbc.com/*", "*://*.bbc.co.uk/*"],
  },
  {
    id: "ported-guardian",
    matches: ["*://www.theguardian.com/*", "*://theguardian.com/*"],
  },
  {
    excludeSelectors: [
      "[promotext]",
      "[data-testid=Leaderboard]",
      "[data-testid=HomeTickerV2]",
      "[data-testid=SiteFooter]",
      "[class^=refinitiv-promo-bar__container]",
      "[data-testid=ResponsiveAdSlot]",
    ],
    id: "ported-reuters",
    matches: ["*://www.reuters.com/*", "*://reuters.com/*"],
  },
  {
    excludeMatches: ["https://www.bloomberg.com/live/*"],
    excludeSelectors: [
      ".ticker-bar",
      "[aria-label=Banner]",
      "aside",
      "[data-component=ticker-bar]",
      "footer.bb-global-footer",
      ".vjs-text-track-display",
    ],
    id: "ported-bloomberg",
    matches: ["*://www.bloomberg.com/*", "*://bloomberg.com/*"],
  },
  {
    extraInlineSelectors: ["span[data-caps='initial']"],
    excludeSelectors: ["footer.ds-footer", ".vjs-text-track-display"],
    injectedCss: [
      "a::before {position:relative!important;}",
      "[class^=button] span font {white-space:pre-wrap;}",
    ],
    id: "ported-economist",
    matches: ["*://www.economist.com/*", "*://economist.com/*"],
  },
  {
    id: "ported-techcrunch",
    matches: ["*://techcrunch.com/*"],
  },
  {
    id: "ported-the-verge",
    matches: ["*://www.theverge.com/*", "*://theverge.com/*"],
  },
  {
    id: "ported-wired",
    matches: ["*://www.wired.com/*", "*://wired.com/*"],
  },
  {
    id: "ported-ars-technica",
    matches: ["*://arstechnica.com/*"],
  },
  {
    id: "ported-ap-news",
    matches: ["*://apnews.com/*"],
  },
  {
    additionalExcludeSelectors: [
      "footer:last-of-type",
      "nav",
      "header div.subtitle-2.w-full",
    ],
    id: "ported-the-atlantic",
    matches: ["*://www.theatlantic.com/*"],
  },
  {
    excludeSelectors: [
      "header",
      "footer",
      "nav",
      "[aria-label='Markets summary']",
    ],
    additionalExtraBlockSelectors: [".series-nav__link-thumbnail"],
    additionalInjectedCss: [
      ".immersive-translate-target-wrapper br {display:none;}",
      ".spcv_list-item .immersive-translate-target-translation-block-wrapper {display:inline-block;margin-top:8px;}",
    ],
    id: "ported-wsj",
    matches: ["*://www.wsj.com/*", "*://cn.wsj.com/*"],
  },
  {
    id: "ported-washington-post",
    matches: ["*://www.washingtonpost.com/*"],
  },
  {
    id: "ported-forbes",
    matches: ["*://www.forbes.com/*"],
  },
  {
    id: "ported-time",
    matches: ["*://time.com/*"],
  },
  {
    id: "ported-cnet",
    matches: ["*://www.cnet.com/*"],
  },
  {
    id: "ported-nikkei",
    matches: ["*://www.nikkei.com/*"],
  },
  {
    additionalExcludeSelectors: ["[data-subtitles-container='true']"],
    additionalMutationExcludeSelectors: ["[data-subtitles-container='true'] *"],
    id: "ported-coindesk",
    matches: ["*://www.coindesk.com/*"],
  },
  {
    selectors: [
      "[data-test-id=card-container]",
      "[data-test-id=comments-section]",
    ],
    excludeSelectors: [
      "[data-test-id=post-page-meta]",
      "header > div:first-child",
    ],
    id: "ported-seeking-alpha",
    matches: ["*://seekingalpha.com/*"],
  },
] as const satisfies readonly Rule[];
