// Generated by scripts/port-rules.ts from Immersive Translate 1.32.7.
// Do not edit by hand; change the curated list or mapper and rerun the script.
import type { Rule } from "../../../shared/types";

export const videoRules = [
  {
    selectors: [
      ".comment-text",
      "#content-text",
      ".media-item-headline",
      ".slim-video-information-title",
      ".yt-spec-button-view-model",
      ".yt-core-attributed-string > span",
      ".yt-core-attributed-string",
      ".shortsLockupViewModelHostMetadataTitle",
      ".YtmCommentRendererText",
      ".ytAttributedStringHost",
      ".title",
    ],
    additionalExcludeSelectors: [
      ".ytp-caption-window-container",
      "text",
      ".imt-caption-container",
      "ytd-live-chat-frame",
      ".ytm-badge-and-byline-item-byline",
      ".captions-text",
      ".ytp-caption-segment",
    ],
    wrapperPrefix: "",
    wrapperSuffix: "",
    atomicBlockSelectors: [".comment-text"],
    injectedCss: [
      ".immersive-translate-target-wrapper img { width: 16px; height: 16px }",
      ".shortsLockupViewModelHostMetadataTitle,h4.compact-media-item-headline {max-height:unset !important;line-clamp:unset !important;overflow:unset !important;-webkit-line-clamp:unset !important;}",
      ".comment-text {max-height:unset;}",
      ".details,.subhead,.video-card-title,.media-item-headline {max-height:unset!important;-webkit-line-clamp:unset!important;}",
      "truncated-text-content {max-height: unset !important;}",
    ],
    additionalMutationExcludeSelectors: [".imt-caption-container *"],
    additionalExtraBlockSelectors: [".caption-visual-line"],
    id: "ported-youtube",
    matches: ["*://youtube.com/*", "*://*.youtube.com/*"],
  },
  {
    additionalExcludeSelectors: [
      ".bpx-player-subtitle-panel-text",
      ".bili-video-card__info--author, .bili-video-card__info--date",
      "#pictures,#note,#info,#footer,#expander-footer,.playinfo,.upname,#bilibili-player",
    ],
    id: "ported-bilibili",
    matches: ["*://www.bilibili.com/*", "*://*.bilibili.com/*"],
  },
  {
    injectedCss: ["[id*='expandable-paragraph'] {max-height:unset!important;}"],
    id: "ported-pixiv",
    matches: ["*://www.pixiv.net/*"],
  },
  {
    additionalExcludeSelectors: [".jw-text-track-container"],
    additionalMutationExcludeSelectors: [".jw-text-track-container *"],
    additionalInjectedCss: ["[class*=overflow] {max-height:unset!important;}"],
    id: "ported-imdb",
    matches: ["*://www.imdb.com/*", "*://m.imdb.com/*"],
  },
  {
    additionalExcludeSelectors: [".player-timedtext", ".source-cue"],
    additionalMutationExcludeSelectors: [".player-timedtext *"],
    id: "ported-netflix",
    matches: ["*://www.netflix.com/browse*", "*://www.netflix.com/title*"],
  },
  {
    additionalExcludeSelectors: ["#dv-web-player"],
    additionalMutationExcludeSelectors: ["#dv-web-player *"],
    id: "ported-prime-video",
    matches: ["*://www.primevideo.com/*", "*://*.amazon.com/*video*"],
  },
  {
    id: "ported-coursera",
    matches: ["*://www.coursera.org/*", "*://*.coursera.org/*"],
  },
  {
    additionalExcludeSelectors: [
      "[data-purpose='captions-cue-text']",
      ".shaka-text-container",
    ],
    additionalMutationExcludeSelectors: [
      "[data-purpose='captions-cue-text'] *",
      ".shaka-text-container *",
    ],
    id: "ported-udemy",
    matches: ["*://*.udemy.com/*"],
  },
  {
    additionalExcludeSelectors: [
      ".closed-captions",
      ".wrapper-video-bottom-section",
      ".secondary-controls",
    ],
    id: "ported-edx",
    matches: ["*://*.edx.org/*"],
  },
  {
    additionalStayOriginalSelectors: [".mathjax-wrapper"],
    id: "ported-khan-academy",
    matches: ["*://*.khanacademy.org/*"],
  },
  {
    additionalExcludeSelectors: ["#video"],
    additionalMutationExcludeSelectors: ["#video *"],
    id: "ported-ted",
    matches: ["*://www.ted.com/*"],
  },
  {
    additionalExcludeSelectors: [".vp-captions", ".vp-captions-line"],
    additionalMutationExcludeSelectors: [
      ".vp-captions *",
      ".vp-captions-line *",
    ],
    selectorMatches: ["iframe[src*='player.vimeo.com']"],
    additionalExtraBlockSelectors: [
      "span.vp-captions-line",
      "span[class^=CaptionsRenderer_]",
    ],
    id: "ported-vimeo",
    matches: ["*://vimeo.com/*", "*://*.vimeo.com/*"],
  },
  {
    additionalExcludeSelectors: [".player"],
    additionalMutationExcludeSelectors: [".player *"],
    id: "ported-dailymotion",
    matches: ["*://*.dailymotion.com/*"],
  },
  {
    additionalExcludeSelectors: [".dss-hls-subtitle-overlay"],
    additionalMutationExcludeSelectors: [".dss-hls-subtitle-overlay *"],
    id: "ported-disney-plus",
    matches: ["*://www.disneyplus.com/*"],
  },
  {
    additionalExcludeSelectors: [".PlayerMetadata__subTitle", ".CaptionBox"],
    id: "ported-hulu",
    matches: ["*://*.hulu.com/*"],
  },
  {
    additionalExcludeSelectors: [
      "[data-testid='playerContainer']",
      "[data-testid='CueBoxContainer']",
    ],
    additionalMutationExcludeSelectors: [
      "[data-testid='playerContainer'] *",
      "[data-testid='CueBoxContainer'] *",
    ],
    id: "ported-max",
    matches: ["*://play.max.com/*", "*://play.hbomax.com/*"],
  },
] as const satisfies readonly Rule[];
